sudo: required
services:
  - docker
    
before_install:
  - docker build -t jnhaux/docker-tst -f Dockerfile.dev .

script:
  - docker run -e CI=true jnhaux/docker-tst npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-tst"
  env: "DockerTst-env"
  bucket_name: "elasticbeanstalk-eu-central-1-756279742449"
  bucket_path: "docker-tst"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"